### ISSUE TITLE
Question about Fig 2.

### ISSUE THREAD

**Issue by VainF** [Egg-Hu/PURER#1]
Hello, thanks for the great work.

I have a question about Fig 2. The generated images look exactly the same as the samples in [CMI](https://arxiv.org/pdf/2105.08584.pdf). But there is no citation or discussion about this. 

* From the paper 
<img width="587" alt="image" src="https://github.com/Egg-Hu/PURER/assets/18592211/d79ff7d7-906c-4f27-bba3-a5adb03e7751">

* From CMI
<img width="278" alt="image" src="https://github.com/Egg-Hu/PURER/assets/18592211/1fb70b87-9324-4330-9a39-a1f113b11cc8">

**Comment by Egg-Hu** [comment]
The inspirations from the great work (CMI) are important for our CVPR work. Therefore, we submit a new arxiv version of our paper, where we add some discussions and the citation of CMI. (The new version is in processing and should be public a few days later.) 
**For the confusion of Fig. 2:**
1) We just use Fig. 2 to illustrate the gap between synthesized and real images. Considering the excellent performance of CMI, we want to emphasize that the gap between synthesized and real images is inevitable even using the latest model inversion method (i.e., CMI).
2) We also visualize our own synthesized images in Fig. 5, which is our qualitative result.

Thanks again for the inspirations from CMI. The new version with the newly added citation of CMI should be public a few days later.
